image: uber/android-build-environment:latest

pipelines:
  default:
    - step:
        script:
          - echo y | android update sdk --filter tools,platform-tools,build-tools-24.0.0,android-24 --no-ui -a # Grab the Android Support Repo which isn't included in the container
          - ./gradlew assembleDebug